logging:
  level: INFO
  loggers:
    com.dropwizard: DEBUG
server:
  registerDefaultExceptionMappers: false
database:
  driverClass: org.postgresql.Driver
  user: dropwizard
  password: dropwizard
  url: jdbc:postgresql://localhost/dropwizard
  properties:
    charSet: UTF-8
  maxWaitForConnection: 1s
  validationQuery: "SELECT 1"
  validationQueryTimeout: 3s
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: true
  evictionInterval: 10s
  minIdleTime: 1 minute
